version: "3.8"
services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./backend/db:/data/db

  backend:
    container_name: backend
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:3000"
    depends_on:
      - mongodb

  frontend:
    container_name: frontend
    build: ./frontend
    env_file:
      - ./backend/.env
    ports:
      - "5173:5173"

volumes:
  data:


